version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  format-check:
    docker:
      - image: gylleus/deep-poop-dev
    steps:
      - run:
          name: format-check
          command: black . --check
  build-and-test:
    docker:
      - image: gylleus/deep-poop-dev
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - python/test:
          pytest: True
      
workflows:
  main:
    jobs:
      - format-check
      - build-and-test
